apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 --file docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: agent
  name: agent
spec:
  ports:
  - name: "12345"
    port: 12345
    targetPort: 12345
  selector:
    io.kompose.service: agent
status:
  loadBalancer: {}
