apiVersion: v1
kind: Service
metadata:
  name: otelcol-prometheus
  labels:
    app: otelcol
spec:
  selector:
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/instance: opentelemetry-demo
  ports:
    - name: metrics
      port: 8888
      targetPort: 8888
