---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
   otel-collector-config.yaml: |
    receivers:
     otlp:
      protocols:
       http:
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - http://localhost:8182
          allowed_headers: ["*"]
   processors:
     batch:
   exporters:
     otlp:
      endpoint: tempo:4317
      tls:
       insecure: true
   service:
     pipelines:
      traces:
       receivers: [otlp]
       processors: [batch]
       exporters: [otlp]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector:0.58.0
        ports:
        - containerPort: 4318
        volumeMounts:
        - name: otel-config-volume
          mountPath: /etc/otel-collector-config.yaml
          subPath: otel-collector-config.yaml
        args: ["--config=/etc/otel-collector-config.yaml"]
      volumes:
      - name: otel-config-volume
        configMap:
          name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: otel-collector
  name: otel-collector
spec:
  ports:
  - name: grpc
    protocol: TCP
    port: 4317
    targetPort: 4317
  - name: http
    protocol: TCP
    port: 55681
    targetPort: 55681
  type: LoadBalancer
  selector:
    app: otel-collector
