---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: petmysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpet-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: petmysql-secret-root
type: kubernetes.io/basic-auth
stringData:
  password: petclinic
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
type: Opaque
stringData:
  username: petclinic
  password: petclinic
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-host
type: Opaque
stringData:
  host: mydb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: petmysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS petclinic;
    ALTER DATABASE petclinic
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;
    CREATE USER 'petclinic'@'%' IDENTIFIED BY 'petclinic';
    GRANT ALL PRIVILEGES ON petclinic.* TO 'petclinic'@'%' IDENTIFIED BY 'petclinic';
    FLUSH PRIVILEGES;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mydb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: petmysql-secret-root
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
                #- name: MYSQL_HOST
                #valueFrom:
                #secretKeyRef:
                #       name: mysql-host
                #key: host
        ports:
        - containerPort: 3306
          name: mydb
        volumeMounts:
        - name: petmysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: petmysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: petmysql-initdb
        configMap:
          name: petmysql-initdb-config
      - name: petmysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysqlpet-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mydb
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
